[package]
name = "hab"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "../build-habitat.rs"
workspace = "../../"

[[bin]]
name = "hab"
doc = false

[dependencies]
base64 = "*"
dirs = "*"
env_logger = "*"
futures = "*"
# Pending upgrade activities in https://github.com/habitat-sh/core/issues/72
hyper = "0.10"
habitat_api_client = { path = "../builder-api-client" }
habitat_common = { path = "../common" }
habitat_core = { path = "../core" }
habitat_http_client = { path = "../http-client" }
habitat-sup-client = { path = "../sup-client" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
# We need to lock here since v0.30.0 bumps to a version of pest that fails to build on Windows.
handlebars = { version = "0.29.1", default-features = false }
lazy_static = "*"
libc = "*"
log = "*"
pbr = "*"
protobuf = "1.5.1"
retry = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
tabwriter = "*"
termcolor = "*"
toml = { version = "*", default-features = false }
url = "*"
walkdir = "*"
tar = "*"
flate2 = "*"
chrono = "*"
atty = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.uuid]
version = "*"
features = ["v4"]

[target.'cfg(windows)'.dependencies]
widestring = "*"
winapi = { version = "*", features = ["winuser", "windef"] }
winreg = "*"

[target.'cfg(target_family = "unix")'.dependencies]
jemallocator = "*"

[dev-dependencies]
tempfile = "*"

[features]
default = []
functional = []
